content = (
    'package com.aicareer.config;\n\n'
    'import com.aicareer.security.JwtAuthFilter;\n'
    'import com.aicareer.security.OAuth2LoginSuccessHandler;\n'
    'import com.aicareer.security.UserDetailsServiceImpl;\n'
    'import lombok.RequiredArgsConstructor;\n'
    'import org.springframework.beans.factory.annotation.Autowired;\n'
    'import org.springframework.beans.factory.annotation.Value;\n'
    'import org.springframework.context.annotation.Bean;\n'
    'import org.springframework.context.annotation.Configuration;\n'
    'import org.springframework.context.annotation.Lazy;\n'
    'import org.springframework.security.authentication.AuthenticationManager;\n'
    'import org.springframework.security.authentication.AuthenticationProvider;\n'
    'import org.springframework.security.authentication.dao.DaoAuthenticationProvider;\n'
    'import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;\n'
    'import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;\n'
    'import org.springframework.security.config.annotation.web.builders.HttpSecurity;\n'
    'import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;\n'
    'import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;\n'
    'import org.springframework.security.config.http.SessionCreationPolicy;\n'
    'import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;\n'
    'import org.springframework.security.crypto.password.PasswordEncoder;\n'
    'import org.springframework.security.web.SecurityFilterChain;\n'
    'import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;\n'
    'import org.springframework.web.cors.CorsConfiguration;\n'
    'import org.springframework.web.cors.CorsConfigurationSource;\n'
    'import org.springframework.web.cors.UrlBasedCorsConfigurationSource;\n\n'
    'import java.util.List;\n\n'
    '@Configuration\n'
    '@EnableWebSecurity\n'
    '@EnableMethodSecurity\n'
    '@RequiredArgsConstructor\n'
    'public class SecurityConfig {\n\n'
    '    private final JwtAuthFilter jwtAuthFilter;\n'
    '    private final UserDetailsServiceImpl userDetailsService;\n\n'
    '    private OAuth2LoginSuccessHandler oAuth2LoginSuccessHandler;\n\n'
    '    @Autowired\n'
    '    public void setOAuth2LoginSuccessHandler(@Lazy OAuth2LoginSuccessHandler handler) {\n'
    '        this.oAuth2LoginSuccessHandler = handler;\n'
    '    }\n\n'
    '    @Value("${app.frontend-url}")\n'
    '    private String frontendUrl;\n\n'
    '    @Bean\n'
    '    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {\n'
    '        http\n'
    '            .csrf(AbstractHttpConfigurer::disable)\n'
    '            .cors(cors -> cors.configurationSource(corsConfigurationSource()))\n'
    '            .sessionManagement(sess -> sess.sessionCreationPolicy(SessionCreationPolicy.STATELESS))\n'
    '            .authorizeHttpRequests(auth -> auth\n'
    '                .requestMatchers(\n'
    '                    "/api/auth/**",\n'
    '                    "/api/jobs/public/**",\n'
    '                    "/api/subscription/plans",\n'
    '                    "/api/subscription/webhook",\n'
    '                    "/actuator/health",\n'
    '                    "/actuator/info",\n'
    '                    "/swagger-ui/**",\n'
    '                    "/v3/api-docs/**"\n'
    '                ).permitAll()\n'
    '                .requestMatchers("/api/admin/**").hasRole("ADMIN")\n'
    '                .requestMatchers("/api/recruiter/**").hasAnyRole("RECRUITER", "ADMIN")\n'
    '                .anyRequest().authenticated()\n'
    '            )\n'
    '            .oauth2Login(oauth2 -> oauth2\n'
    '                .successHandler(oAuth2LoginSuccessHandler)\n'
    '            )\n'
    '            .authenticationProvider(authenticationProvider())\n'
    '            .addFilterBefore(jwtAuthFilter, UsernamePasswordAuthenticationFilter.class);\n\n'
    '        return http.build();\n'
    '    }\n\n'
    '    @Bean\n'
    '    public CorsConfigurationSource corsConfigurationSource() {\n'
    '        CorsConfiguration config = new CorsConfiguration();\n'
    '        config.setAllowedOrigins(List.of(frontendUrl, "http://localhost:5173", "http://localhost:3000"));\n'
    '        config.setAllowedMethods(List.of("GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"));\n'
    '        config.setAllowedHeaders(List.of("*"));\n'
    '        config.setAllowCredentials(true);\n'
    '        config.setMaxAge(3600L);\n\n'
    '        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();\n'
    '        source.registerCorsConfiguration("/**", config);\n'
    '        return source;\n'
    '    }\n\n'
    '    @Bean\n'
    '    public AuthenticationProvider authenticationProvider() {\n'
    '        DaoAuthenticationProvider provider = new DaoAuthenticationProvider();\n'
    '        provider.setUserDetailsService(userDetailsService);\n'
    '        provider.setPasswordEncoder(passwordEncoder());\n'
    '        return provider;\n'
    '    }\n\n'
    '    @Bean\n'
    '    public AuthenticationManager authenticationManager(AuthenticationConfiguration config) throws Exception {\n'
    '        return config.getAuthenticationManager();\n'
    '    }\n\n'
    '    @Bean\n'
    '    public PasswordEncoder passwordEncoder() {\n'
    '        return new BCryptPasswordEncoder();\n'
    '    }\n'
    '}\n'
)

target = r'c:\Users\Muniyappan R\Downloads\Resume-Ultimate\backend\src\main\java\com\aicareer\config\SecurityConfig.java'
with open(target, 'w', encoding='utf-8') as f:
    f.write(content)
print('Written OK, chars:', len(content))
