services:

  - type: web
    name: umaiya-backend
    env: docker
    repo: https://github.com/developerkrishnagiri/Umaiya-AI-Resume-Maker
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: umaiya-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: umaiya-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: umaiya-db
          property: password

  - type: web
    name: umaiya-frontend
    env: static
    repo: https://github.com/developerkrishnagiri/Umaiya-AI-Resume-Maker
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build

databases:

  - name: umaiya-db
